---
# Copyright 2022, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setup deploy host
  hosts: deploy_hosts
  gather_facts: true
  environment: "{{ deployment_environment_variables | default({}) }}"
  become: true
  vars_files:
  - vars/main.yml
  tags:
    - deploy-osa
  tasks:
    - debug:
        msg: "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"

    - name: Gather variables for each operating system
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"
      tags:
        - always

    - name: Get OSA
      git:
        repo: "{{ osa_repo | default('https://opendev.org/openstack/openstack-ansible') }}"
        dest: /opt/openstack-ansible
        version: "{{ osa_branch | default('master') }}"
      when:
        - pre_config_osa | default(true) | bool
        - clone_osa | default(true) | bool

    - name: Create OSA configuration directory
      file:
        path: "/etc/openstack_deploy"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"
      when:
        - pre_config_osa | default(true) | bool

    - name: Create OSA group_vars directory
      file:
        path: "/etc/openstack_deploy/group_vars"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"
      when:
        - pre_config_osa | default(true) | bool

    - name: Copy default config files and directories
      shell: >-
        rsync
        -av
        --include='*.yml'
        --include='*/'
        --exclude='*'
        /opt/openstack-ansible/etc/openstack_deploy/
        /etc/openstack_deploy/
      args:
        executable: /bin/bash
        chdir: /opt/openstack-ansible
        warn: no
      when:
        - pre_config_osa | default(true) | bool

    - name: Drop osa config (OVN)
      template:
        src: "01_openstack_user_config.j2"
        dest: /etc/openstack_deploy/openstack_user_config.yml
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool
        - osa_neutron_plugin == "ml2.ovn"

    - name: Drop osa config (OVS)
      template:
        src: "02_openstack_user_config.j2"
        dest: /etc/openstack_deploy/openstack_user_config.yml
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool
        - osa_neutron_plugin == "ml2.ovs"

    - name: Drop osa user variables (OVN)
      template:
        src: "01_user_mnaio_variables.j2"
        dest: /etc/openstack_deploy/user_mnaio_variables.yml
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool
        - osa_neutron_plugin == "ml2.ovn"

    - name: Drop osa user variables (OVS)
      template:
        src: "02_user_mnaio_variables.j2"
        dest: /etc/openstack_deploy/user_mnaio_variables.yml
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool
        - osa_neutron_plugin == "ml2.ovs"

    - name: Drop config to disable serial throttle settings
      template:
        src: "user_unserial_variables.j2"
        dest: /etc/openstack_deploy/user_unserial_variables.yml
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool
        - osa_disable_serial | default(false) | bool

    - name: Drop OVS group_vars config
      template:
        src: "ovs_network_hosts_group.j2"
        dest: "/etc/openstack_deploy/group_vars/network_hosts"
        mode: "0644"
        owner: root
        group: root
      when:
        - pre_config_osa | default(true) | bool

    - name: Ensure the user_variables file is populated
      lineinfile:
        path: /etc/openstack_deploy/user_variables.yml
        regexp: '^{{ item }}'
        line: '{{ item }}'
        create: yes
      with_items:
        - '---'
        - 'osa_ops_mnaio: true'
      when:
        - pre_config_osa | default(true) | bool

    - name: Bootstrap ansible
      command: bash ./scripts/bootstrap-ansible.sh
      args:
        chdir: /opt/openstack-ansible
      when:
        - run_osa | default(true) | bool

    - name: Create passwords
      command: ./scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
      args:
        chdir: /opt/openstack-ansible
      when:
        - run_osa | default(true) | bool

    - name: Config Tmux
      lineinfile:
        path: /root/.tmux.conf
        regexp: '^set-option'
        line: 'set-option -g history-limit 20000'
        owner: root
        group: root
        mode: 0644
        create: yes

    - name: Run OSA
      command: "{{ item }}"
      args:
        chdir: /opt/openstack-ansible/playbooks
      with_items:
        - tmux new-session -d -s build-osa
        - tmux select-pane -t 0
        - tmux send-keys "ulimit -n 10240" C-m
#        - tmux send-keys "openstack-ansible setup-hosts.yml setup-infrastructure.yml setup-openstack.yml" C-m
      when:
        - inventory_hostname == groups['deploy_hosts'][0]
        - run_osa | default(true) | bool

    - name: Finished notice
      debug:
        msg: |
          OSA deploy running. To check on the state of this deployment, login
          to the {{ groups['deploy_hosts'][0] }} VM ({{ ansible_ssh_host }}) and attach to the "build-osa" tmux session.
      when:
        - run_osa | default(true) | bool
